export const CONFIG = {
  PORT: 3000,
  RAINFOREST_API: "YOUR_RAINFOREST_API_KEY",
  EARNKARO_API: "YOUR_EARNKARO_API_KEY",
  BLOGGER_API: "YOUR_BLOGGER_API_KEY",
  BLOG_ID: "YOUR_BLOG_ID",
  BOT_TOKEN: "YOUR_TELEGRAM_BOT_TOKEN",
  CHANNEL_ID: "@yourchannel"
};
